### ISSUE TITLE
Made with Manubot

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot.org#10]
@dhimmel @agitter @slochower Please suggest some manuscripts that we can include in the "Made With Manubot" section. In this issue I'd like to come up with an in-order list of 5 to 10 manuscripts to feature.

Then I'll go a pull some nice screenshots from them as well as some metadata to show on hover or something.

**Comment by dhimmel** [comment]
Many of the most prominent examples are listed in [Meta Review](https://greenelab.github.io/meta-review/v/362b839108fdcb109ede7dc29a2492303cec62fe/#existing-manuscripts). The ones that come to mind are:

+ https://github.com/greenelab/deep-review
+ https://github.com/Benjamin-Lee/deep-rules
+ https://jmonlong.github.io/manu-vgsv/
+ https://openclimatedata.github.io/global-emissions/
+ https://trang1618.github.io/tpot-fss-ms/
+ https://simonvh.github.io/gimmemotifs-manuscript/
+ https://github.com/greenelab/scihub-manuscript
+ https://git.dhimmel.com/rephetio-manuscript/

**Comment by vincerubinetti** [comment]
I also liked @slochower 's chemistry-related paper with the cool figures. Can we include that?

**Comment by slochower** [comment]
Sure!
https://slochower.github.io/smirnoff-host-guest-manuscript/

**Comment by dhimmel** [comment]
Another excellent one is https://laurentperrinet.github.io/2019-05_illusions-visuelles/ (more info at https://github.com/manubot/rootstock/pull/213#issuecomment-501648571). It may be nice to showcase this one because it is in another language and on a different topic.

**Comment by vincerubinetti** [comment]
Full catalog is up per #15 and short list of showcased manuscripts has been on the main landing page for a while.
