### ISSUE TITLE
Rebuild manubot.org/catalog when upstream catalog updates

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot.org#22]
https://manubot.org/catalog/ is generated here from the `catalog.json` file created by https://github.com/manubot/catalog. When a commit is made to the `master` branch of `manubot/catalog`, then `catalog.json` is generated by CI and deployed to https://manubot.github.io/catalog/catalog.json. However, this repository doesn't then automatically rebuild. Until this repository is rebuilt, the updated catalog data won't display at https://manubot.org/catalog/.

I've enabled a Travis cron job to run CI once a day:

> ![image](https://user-images.githubusercontent.com/1117703/60818430-a0a12a00-a16b-11e9-8214-e0240efd96e8.png)

Therefore, updates to `manubot/catalog` should deploy to the website within a day.

However, we could also consider whether the `manubot/catalog` CI deployment should trigger a `manubot.org` build, as [discussed here](https://stackoverflow.com/questions/32118067/triggering-builds-of-dependent-projects-in-travis-ci).

**Comment by agitter** [comment]
Is there any downside to having `manubot/catalog` CI deployment trigger a build here? That sounds appealing to me.

**Comment by dhimmel** [comment]
More setup & possibility of leaking the Travis API credentials are the downsides I could imagine.

**Comment by dhimmel** [comment]
References:

+ https://github.com/plume-lib/trigger-travis

**Comment by dhimmel** [comment]
I created @manubot-catalog-travis-bot which only has write access to `manubot/manubot.org`. I think if we use the Travis API Token for this user, it will be more limited in scope and hence less catastrophic if it leaks.

**Comment by dhimmel** [comment]
Okay triggering Travis builds is working! Added in https://github.com/manubot/catalog/commit/c16228ba41aacea1eeddb646ea783a0dbe3d129c.

See for example the following commit and resulting CI builds:

1. https://github.com/manubot/catalog/commit/ea8a80a59aeebfd33afce2a3bce14ccf5520360f
2. https://travis-ci.com/manubot/catalog/builds/118362914#L267
3. https://travis-ci.com/manubot/manubot.org/builds/118363064

One annoying thing is that Travis seems to truncate the message, cutting the URL of the triggering build. I'll go ahead and disable `manubot/manubot.org` cron jobs.

**Comment by dhimmel** [comment]
In https://github.com/manubot/catalog/commit/a503ba54e79cb3d42cec45306f3455d999298b93, I update the deployment to only trigger a `manubot.org` build if the gh-pages commit is non-empty (i.e. gh-pages files have changed).

**Comment by agitter** [comment]
Very cool.  This looks like a great solution.

**Comment by agitter** [comment]
@dhimmel do we still want some cron jobs in `manubot/manubot.org` or more likely `manubot/catalog`?  If we don't add new manuscripts to the catalog frequently, we won't pull in metadata changes like https://github.com/manubot/try-manubot/pull/6  Those cron jobs may not need to be very frequent.

**Comment by dhimmel** [comment]
> If we don't add new manuscripts to the catalog frequently, we won't pull in metadata changes

I set https://travis-ci.com/manubot/catalog/settings to run weekly cron jobs:

![image](https://user-images.githubusercontent.com/1117703/60907399-6e64fa80-a247-11e9-8398-f4f159b04da8.png)

Therefore, manubot.org/catalog should never be more than a week out of date (unless an upstream build fails).
